[package]
name = "fusionamm-client_integration_solana_v2_0"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
solana-program = { version = "~2.0.25" }
fusionamm-client = { path = "../../../client" }
